### ISSUE TITLE
Rekomendasi Tutorial

### ISSUE THREAD

**Issue by ghost** [lejaaprianza/reactjs-lampungkode#1]
Dear, Pemilik Repo.

Kemarin saya lihat reponya aktif sekali dengan React, mungkin anda tertarik dengan Framework untuk React : Next JS.

- [Halaman Rumah Next JS](https://nextjs.org/)

Terima Kasih

**Comment by lejaaprianza** [comment]
Hehe thank you for recom kak :) kebetulan banget baru2 ini aku juga baru baca tutorial next js 😄
